# 应用配置
app:
  version: 1.0   # 系统当前版本号
  aopLogOpen: 1   # 是否开启aop日志 0关闭，1开启
  ioEncryptOpen: 0  # 是否开启输入输出加密 0关闭，1开启
  aesKey: 123   # aes加密key

auth:
  excludes: login,logout,static,captcha   # 不做授权校验的URL

#
spring:
## mysql 配置
  redis:
    host: 172.18.36.120
    database: 0

#
logging:
  level:
    com.su: debug
#logging.level.org.springframework.transaction=debug
    org.mybatis: debug
  file: /var/log/java/system.log


